services:
  portal:
    container_name: portal
    networks:
      - srv-network
    build: ./
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./portal:/usr/app

networks:
  srv-network:
   external: true