services:
  portal:
    container_name: portal
    networks:
      - srv-network
    build: ./
    restart: always
    ports:
      - "4000:4000"
    expose:
      - "4000:4000"
    volumes:
      - ./portal:/usr/app

networks:
  srv-network:
   external: true